# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Julia & Vincent
description: > # this means to ignore newlines until "baseurl:"
  Le 23 Septembre 2017, Julia & Vincent vous invite à célébrer leur mariage.
url: "http://www.juliaetvincent.ovh" # the base hostname & protocol for your site
baseurl: ""
absolute_url: "http://www.juliaetvincent.ovh"
form_email: "helmut.perchue@gmail.com"

# Build settings
markdown: kramdown

